import styles from '@styles/globals.module.scss';
import cn from 'classnames';
import { Rubik } from 'next/font/google';

const rubik = Rubik({
    subsets: ['latin'],
    weight: ['400', '500'],
    variable: '--font-rubik'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(styles.main, rubik.variable)}>{children}</body>
    </html>
  )
}
