import "@styles/normalize.scss";
import "@styles/global.scss";
import "@fortawesome/fontawesome-svg-core/styles.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
